"use client";

export const COMPANY_SIZES = [
  { value: "1", label: "Just me (Solopreneur)" },
  { value: "1-10", label: "1-10 employees" },
  { value: "11-50", label: "11-50 employees" },
  { value: "51-200", label: "51-200 employees" },
  { value: "201-500", label: "201-500 employees" },
  { value: "501-1000", label: "501-1000 employees" },
  { value: "1001-5000", label: "1001-5000 employees" },
  { value: "5000+", label: "Enterprise (5000+)" },
];

export const GENERIC_DOCUMENT_SUGGESTIONS = [
  "Company overview / About us",
  "Organization chart & team list",
  "List of products or services",
  "Standard operating procedures (SOPs)",
  "Pricing sheet or rate card",
  "Customer or vendor contracts",
  "Marketing or sales playbook",
  "Goals, OKRs or quarterly plans",
];

export const DOCUMENT_TYPE_HINTS: Record<string, string> = {
  "Company overview / About us": "PDF, DOCX",
  "Organization chart & team list": "PDF, XLSX, DOCX",
  "List of products or services": "PDF, XLSX, DOCX",
  "Standard operating procedures (SOPs)": "PDF, DOCX",
  "Pricing sheet or rate card": "PDF, XLSX",
  "Customer or vendor contracts": "PDF, DOCX",
  "Marketing or sales playbook": "PDF, DOCX, PPTX",
  "Goals, OKRs or quarterly plans": "PDF, XLSX, DOCX",
};

export const INDUSTRY_FILE_SUGGESTIONS: Record<string, string[]> = {
  "Technology & Software": [
    "Technical architecture docs",
    "Product roadmaps",
    "Tech stack documentation",
    "Software requirements specifications",
    "API documentation",
  ],
  "IT Services & Consulting": [
    "Client project summaries",
    "Service level agreements",
    "Resource allocation plans",
    "Case studies",
    "Consulting frameworks",
  ],
  "Artificial Intelligence & Machine Learning": [
    "Model architecture docs",
    "AI ethics guidelines",
    "Performance benchmarks",
    "Research notes",
  ],
  "SaaS / Cloud Computing": [
    "Subscription metrics",
    "Infrastructure diagrams",
    "SLA documents",
    "Customer onboarding guides",
    "Feature release notes",
  ],
  "Cybersecurity": [
    "Security audit reports",
    "Threat assessment docs",
    "Compliance certifications",
    "Incident response plans",
  ],
  "E-commerce & Online Retail": [
    "Product catalogs",
    "Sales analytics reports",
    "Customer segmentation data",
    "Inventory management sheets",
    "Return/refund policies",
  ],
  "Fintech & Payment Solutions": [
    "Transaction flow diagrams",
    "Compliance documentation",
    "Security audit reports",
    "Financial projections",
  ],
  "Banking & Financial Services": [
    "Financial statements (P&L, Balance Sheet)",
    "Cash flow reports",
    "Risk assessment documents",
    "Customer portfolio data",
  ],
  "Insurance & Risk Management": [
    "Policy documents",
    "Claims processing workflows",
    "Risk assessment models",
    "Customer retention data",
  ],
  "Investment & Wealth Management": [
    "Investment portfolios",
    "Market analysis reports",
    "Client financial plans",
    "Regulatory filings",
  ],
  "Healthcare & Life Sciences": [
    "Patient flow diagrams",
    "Staff scheduling templates",
    "Medical inventory records",
    "Compliance documentation",
  ],
  "Healthcare Technology (HealthTech)": [
    "EHR integration docs",
    "Telehealth platform specs",
    "HIPAA compliance docs",
    "Patient engagement metrics",
  ],
  "Pharmaceuticals & Biotech": [
    "Drug development pipelines",
    "Clinical trial reports",
    "Regulatory submission docs",
    "Manufacturing SOPs",
  ],
  "Medical Devices & Equipment": [
    "Product specifications",
    "FDA/CE certification docs",
    "Manufacturing processes",
    "Distribution agreements",
  ],
  "Telemedicine & Digital Health": [
    "Platform architecture docs",
    "Patient consent forms",
    "Telehealth guidelines",
    "Data privacy policies",
  ],
  "Education & EdTech": [
    "Curriculum documents",
    "Student enrollment data",
    "Teacher/staff schedules",
    "Learning analytics reports",
  ],
  "Online Learning & E-Learning": [
    "Course catalogs",
    "Student engagement metrics",
    "Content development plans",
    "Certification frameworks",
  ],
  "Higher Education": [
    "Academic program docs",
    "Admission statistics",
    "Research publications",
    "Accreditation documents",
  ],
  "Training & Development": [
    "Training curriculum",
    "Skill assessment tools",
    "Participant feedback reports",
    "Certification programs",
  ],
  "Manufacturing & Industrial": [
    "Production schedules",
    "Quality control reports",
    "Equipment maintenance logs",
    "Safety compliance docs",
  ],
  "Automotive & Electric Vehicles": [
    "Vehicle specifications",
    "Supply chain documents",
    "Safety test reports",
    "Manufacturing processes",
  ],
  "Aerospace & Defense": [
    "Engineering specifications",
    "Safety certifications",
    "Contract documents",
    "Compliance reports",
  ],
  "Electronics & Semiconductors": [
    "Circuit designs",
    "Manufacturing specs",
    "Quality assurance reports",
    "Product testing results",
  ],
  "Retail & Consumer Goods": [
    "Inventory management sheets",
    "Sales reports",
    "Supplier lists",
    "Customer purchase history",
  ],
  "Fashion & Apparel": [
    "Design portfolios",
    "Seasonal collections",
    "Supplier agreements",
    "Brand guidelines",
  ],
  "Food & Beverage": [
    "Recipe documentation",
    "Supply chain records",
    "Quality control reports",
    "Distribution agreements",
  ],
  "Beauty & Cosmetics": [
    "Product formulations",
    "Regulatory compliance docs",
    "Marketing campaigns",
    "Sales analytics",
  ],
  "Sports & Fitness": [
    "Training programs",
    "Member analytics",
    "Facility schedules",
    "Equipment inventories",
  ],
  "Real Estate & Property": [
    "Property listings",
    "Lease agreements",
    "Maintenance schedules",
    "Market analysis reports",
  ],
  "Construction & Infrastructure": [
    "Project blueprints",
    "Contractor agreements",
    "Safety compliance docs",
    "Progress reports",
  ],
  "Architecture & Interior Design": [
    "Design portfolios",
    "Project specifications",
    "Client briefs",
    "Material specifications",
  ],
  "Media & Entertainment": [
    "Content calendars",
    "Audience analytics",
    "Campaign performance reports",
    "Production schedules",
  ],
  "Film & Television": [
    "Production schedules",
    "Script documents",
    "Budget breakdowns",
    "Distribution agreements",
  ],
  "Music & Audio": [
    "Track catalogs",
    "Licensing agreements",
    "Royalty statements",
    "Production schedules",
  ],
  "Gaming & Esports": [
    "Game design documents",
    "Player analytics",
    "Monetization strategies",
    "Development roadmaps",
  ],
  "Publishing & Content": [
    "Editorial calendars",
    "Content guidelines",
    "Readership analytics",
    "Distribution plans",
  ],
  "Advertising & Marketing": [
    "Campaign briefs",
    "Client portfolios",
    "Performance reports",
    "Media buying plans",
  ],
  "Digital Marketing & SEO": [
    "SEO audit reports",
    "Content calendars",
    "Campaign analytics",
    "Keyword research docs",
  ],
  "Public Relations & Communications": [
    "Press release archives",
    "Media coverage reports",
    "Crisis communication plans",
    "Stakeholder maps",
  ],
  "Logistics & Supply Chain": [
    "Route maps",
    "Fleet management data",
    "Shipping manifests",
    "Warehouse inventory",
  ],
  "Transportation & Mobility": [
    "Fleet schedules",
    "Route optimization docs",
    "Maintenance logs",
    "Customer analytics",
  ],
  "Travel & Tourism": [
    "Booking analytics",
    "Destination guides",
    "Vendor agreements",
    "Seasonal pricing strategies",
  ],
  "Hospitality & Hotels": [
    "Occupancy reports",
    "Guest feedback data",
    "Staff schedules",
    "Revenue management docs",
  ],
  "Restaurants & Food Services": [
    "Menu documentation",
    "Supplier agreements",
    "Health inspection reports",
    "Sales analytics",
  ],
  "Legal Services & Law": [
    "Case files",
    "Legal research docs",
    "Client agreements",
    "Compliance checklists",
  ],
  "Accounting & Taxation": [
    "Financial statements",
    "Tax filing documents",
    "Audit reports",
    "Compliance checklists",
  ],
  "HR & Recruitment": [
    "Job descriptions",
    "Candidate pipelines",
    "Interview frameworks",
    "Employee handbooks",
  ],
  "Staffing & Outsourcing": [
    "Client requirements docs",
    "Service level agreements",
    "Billing schedules",
    "Quality metrics",
  ],
  "Non-profit & NGO": [
    "Grant applications",
    "Impact reports",
    "Donor databases",
    "Program evaluations",
  ],
  "Government & Public Sector": [
    "Policy documents",
    "Budget allocations",
    "Public records",
    "Service delivery metrics",
  ],
  "Energy & Utilities": [
    "Infrastructure maps",
    "Consumption reports",
    "Regulatory filings",
    "Environmental impact docs",
  ],
  "Oil & Gas": [
    "Exploration reports",
    "Production data",
    "Safety compliance docs",
    "Supply chain docs",
  ],
  "Renewable Energy & Sustainability": [
    "Project feasibility studies",
    "Environmental impact docs",
    "Energy production data",
    "Regulatory permits",
  ],
  "Agriculture & AgTech": [
    "Crop management plans",
    "Soil analysis reports",
    "Supply chain docs",
    "Regulatory compliance",
  ],
  "Environment & Climate": [
    "Environmental assessments",
    "Climate data reports",
    "Regulatory filings",
    "Conservation plans",
  ],
  "Telecommunications": [
    "Network architecture docs",
    "Service level agreements",
    "Customer analytics",
    "Infrastructure maps",
  ],
  "Broadcasting & Media": [
    "Programming schedules",
    "Audience analytics",
    "Content rights docs",
    "Advertising contracts",
  ],
  "Sports Management": [
    "Athlete contracts",
    "Event schedules",
    "Sponsorship agreements",
    "Performance metrics",
  ],
  "Event Management": [
    "Event timelines",
    "Vendor contracts",
    "Budget breakdowns",
    "Attendee analytics",
  ],
  "Non-governmental Organization": [
    "Project proposals",
    "Impact assessments",
    "Donor reports",
    "Compliance documents",
  ],
  "Social Enterprise": [
    "Impact metrics",
    "Business plans",
    "Funding proposals",
    "Community engagement docs",
  ],
  "Research & Development": [
    "Research proposals",
    "Experiment logs",
    "Publication records",
    "Patent applications",
  ],
  "Science & Laboratories": [
    "Lab protocols",
    "Research data",
    "Safety documentation",
    "Equipment inventories",
  ],
};

export const MICRO_VERTICAL_FILE_SUGGESTIONS: Record<string, string[]> = {
  "Custom Software Development": [
    "Software architecture diagrams",
    "Client project portfolios",
    "Development process docs",
    "Technology stack documentation",
  ],
  "Mobile App Development": [
    "App store listings",
    "UI/UX design files",
    "User analytics reports",
    "Release notes",
  ],
  "Web Development": [
    "Website architecture docs",
    "Client portfolio sites",
    "Performance reports",
    "Design mockups",
  ],
  "Cloud Services & Migration": [
    "Cloud architecture diagrams",
    "Migration plans",
    "Cost optimization reports",
    "SLA documents",
  ],
  "Data Analytics & Business Intelligence": [
    "Dashboard screenshots",
    "Data pipeline docs",
    "Client case studies",
    "Sample reports",
  ],
  "Machine Learning & AI Solutions": [
    "Model architecture docs",
    "Performance benchmarks",
    "Use case documents",
    "AI ethics guidelines",
  ],
  "DevOps & Infrastructure": [
    "CI/CD pipeline docs",
    "Infrastructure diagrams",
    "Monitoring dashboards",
    "Security policies",
  ],
  "API Development & Integration": [
    "API documentation",
    "Integration guides",
    "Architecture diagrams",
    "Testing reports",
  ],
  "E-commerce Platforms": [
    "Platform feature docs",
    "Merchant onboarding guides",
    "Payment integration docs",
    "Security certifications",
  ],
  "Payment Processing": [
    "Payment flow diagrams",
    "Security certifications",
    "Compliance documents",
    "Transaction reports",
  ],
  "Digital Marketing": [
    "Campaign portfolios",
    "ROI reports",
    "Content calendars",
    "Analytics dashboards",
  ],
  "Content Management Systems": [
    "CMS architecture docs",
    "User guides",
    "Security assessments",
    "Performance benchmarks",
  ],
  "Project Management Tools": [
    "Feature documentation",
    "User guides",
    "Integration docs",
    "Roadmap documents",
  ],
  "Customer Relationship Management (CRM)": [
    "CRM workflow docs",
    "Integration guides",
    "Customer journey maps",
    "Security certifications",
  ],
  "Enterprise Resource Planning (ERP)": [
    "Module documentation",
    "Implementation guides",
    "Integration specs",
    "Security assessments",
  ],
  "Human Resources (HR) Software": [
    "Feature documentation",
    "Compliance guides",
    "User manuals",
    "Security certifications",
  ],
  "Telehealth & Remote Care": [
    "Platform architecture docs",
    "HIPAA compliance docs",
    "Patient flow diagrams",
    "User guides",
  ],
  "Electronic Health Records (EHR)": [
    "EHR system specs",
    "Interoperability docs",
    "Compliance certifications",
    "User training materials",
  ],
  "Medical Imaging & Diagnostics": [
    "Imaging protocols",
    "Diagnostic accuracy reports",
    "Regulatory approvals",
    "Clinical validation docs",
  ],
  "Drug Discovery & Research": [
    "Research protocols",
    "Clinical trial data",
    "Regulatory submissions",
    "Patent applications",
  ],
  "Online Education Platforms": [
    "Course catalogs",
    "Student analytics",
    "Content development plans",
    "User engagement reports",
  ],
  "Corporate Training": [
    "Training curriculum",
    "Assessment tools",
    "Participant feedback",
    "ROI reports",
  ],
  "Skill Development": [
    "Skill frameworks",
    "Learning paths",
    "Assessment tools",
    "Certification programs",
  ],
  "Fintech Solutions": [
    "Product documentation",
    "Security audits",
    "Compliance certifications",
    "Financial projections",
  ],
  "Blockchain & Crypto": [
    "Whitepapers",
    "Smart contract audits",
    "Tokenomics docs",
    "Technical architecture",
  ],
  "Insurtech": [
    "Product documentation",
    "Underwriting guidelines",
    "Claims processing flows",
    "Customer analytics",
  ],
  "Supply Chain Management": [
    "Supply chain maps",
    "Vendor contracts",
    "Inventory reports",
    "Risk assessments",
  ],
  "Warehouse Management": [
    "Warehouse layouts",
    "Inventory reports",
    "Process documentation",
    "Equipment specs",
  ],
  "Fleet Management": [
    "Fleet inventory",
    "Maintenance schedules",
    "Route optimization docs",
    "Compliance reports",
  ],
  "Last Mile Delivery": [
    "Delivery route maps",
    "Driver schedules",
    "Customer feedback data",
    "Performance metrics",
  ],
  "Social Media & Networking": [
    "Platform architecture docs",
    "User growth metrics",
    "Content moderation policies",
    "Monetization strategies",
  ],
  "Video Streaming & OTT": [
    "Content library docs",
    "Streaming architecture",
    "User analytics",
    "Monetization plans",
  ],
  "Online Gaming": [
    "Game design documents",
    "Player analytics",
    "Monetization strategies",
    "Community guidelines",
  ],
  "Virtual Reality (VR) & Augmented Reality (AR)": [
    "Experience design docs",
    "Technical specifications",
    "User testing reports",
    "Content pipelines",
  ],
  "Internet of Things (IoT)": [
    "Device specifications",
    "Network architecture",
    "Security protocols",
    "Data flow diagrams",
  ],
  "Robotics & Automation": [
    "Robot specifications",
    "Integration guides",
    "Safety protocols",
    "Performance benchmarks",
  ],
  "Electric Vehicles & Charging": [
    "Vehicle specifications",
    "Charging infrastructure docs",
    "Battery technology docs",
    "Market analysis",
  ],
  "Smart Buildings & Homes": [
    "System architecture docs",
    "Device integration guides",
    "Security protocols",
    "Energy efficiency reports",
  ],
  "Clean Energy Solutions": [
    "Project feasibility studies",
    "Energy production data",
    "Environmental impact docs",
    "Investment proposals",
  ],
  "Waste Management": [
    "Collection schedules",
    "Processing facility docs",
    "Recycling reports",
    "Equipment inventories",
  ],
  "Water Treatment": [
    "Treatment process docs",
    "Quality testing reports",
    "Infrastructure maps",
    "Regulatory compliance",
  ],
  "Agriculture Technology": [
    "Crop management plans",
    "Sensor data reports",
    "Yield predictions",
    "Equipment specifications",
  ],
  "Food Technology": [
    "Product formulations",
    "Quality control reports",
    "Supply chain docs",
    "Regulatory compliance",
  ],
  "B2B Services": [
    "Service catalogs",
    "Client case studies",
    "SLA documents",
    "Partnership agreements",
  ],
  "B2C Services": [
    "Product catalogs",
    "Customer analytics",
    "Marketing plans",
    "User feedback data",
  ],
  "Marketplace & Platforms": [
    "Platform architecture docs",
    "Seller onboarding guides",
    "Transaction flow docs",
    "Growth metrics",
  ],
  "Subscription Services": [
    "Subscription plans",
    "Churn analysis reports",
    "Customer lifecycle docs",
    "Feature roadmaps",
  ],
  "Managed Services": [
    "Service catalogs",
    "SLA documents",
    "Monitoring reports",
    "Security policies",
  ],
  "Consulting & Advisory": [
    "Consulting frameworks",
    "Client deliverables",
    "Case studies",
    "Methodology documents",
  ],
};
